workflows:
  build-app:
    name: Build Aviator Bot APK
    max_build_duration: 10
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies and build APK
        script: |
          flutter pub get
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
